- name: Clonar repositorio del proyecto PadelManager
  command: git clone {{github_repository.download_url}}

- name: Compilación del proyecto PadelManager
  become: yes
  shell: mvn clean install -DskipTests
  args:
    chdir: /home/vagrant/PadelManager/padelmanager

- name: Ejecución del servicio PadelManager
  become: yes
  shell: nohup mvn spring-boot:start &
  args:
    chdir: /home/vagrant/PadelManager/padelmanager
